server:
  tomcat:
    uri-encoding: UTF-8
  port: 5000
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  
spring:
  mandatory-file-encoding: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    sqlScriptEncoding: UTF-8
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-107-20-104-234.compute-1.amazonaws.com:5432/ddg8afkmuiabtv
    username: wyzsjswuckvhai
    password: 619faddea2365680b52f4db965943935b1d6f5c66c1be19d4b419a9d09a81327
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect