server:
  tomcat:
    uri-encoding: UTF-8
  port: ${PORT:5000}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  
spring:
  mandatory-file-encoding: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    sqlScriptEncoding: UTF-8
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect