server:
  tomcat:
    uri-encoding: UTF-8
  port: ${PORT:5000}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  
spring:
  mandatory-file-encoding: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    initialization-mode: always
    data:
    - classpath:data.sql
    sqlScriptEncoding: UTF-8
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost/stockpymes?user=postgres&password=root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        
stockpymes:
    cmd:
        jwtExpirationMs: 86400000
        jwtSecret: claveSecreta7
  
  